package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/wwwwshwww/spot-sandbox/graph/model"
	cluster_element_graph "github.com/wwwwshwww/spot-sandbox/internal/adapter/inbound/cluster_element/graph"
	dbscan_profile_graph "github.com/wwwwshwww/spot-sandbox/internal/adapter/inbound/dbscan_profile/graph"
	spot_graph "github.com/wwwwshwww/spot-sandbox/internal/adapter/inbound/spot/graph"
	spots_profile_graph "github.com/wwwwshwww/spot-sandbox/internal/adapter/inbound/spots_profile/graph"
	dbscan_profile_mysql "github.com/wwwwshwww/spot-sandbox/internal/adapter/outbound/dbscan_profile/dbscan_profile/mysql"
	dbscan_profile_finder_mysql "github.com/wwwwshwww/spot-sandbox/internal/adapter/outbound/dbscan_profile/dbscan_profile_finder/mysql"
	spot_mysql "github.com/wwwwshwww/spot-sandbox/internal/adapter/outbound/spot/spot/mysql"
	spot_finder_mysql "github.com/wwwwshwww/spot-sandbox/internal/adapter/outbound/spot/spot_finder/mysql"
	spots_profile_mysql "github.com/wwwwshwww/spot-sandbox/internal/adapter/outbound/spots_profile/spots_profile/mysql"
	spots_profile_finder_mysql "github.com/wwwwshwww/spot-sandbox/internal/adapter/outbound/spots_profile/spots_profile_finder/mysql"
	"github.com/wwwwshwww/spot-sandbox/internal/common"
	"github.com/wwwwshwww/spot-sandbox/internal/domain/spot/spot_finder"
	"github.com/wwwwshwww/spot-sandbox/internal/domain_service"
	"github.com/wwwwshwww/spot-sandbox/internal/usecase/cluster_element"
	"github.com/wwwwshwww/spot-sandbox/internal/usecase/dbscan_profile"
	"github.com/wwwwshwww/spot-sandbox/internal/usecase/spot"
	"github.com/wwwwshwww/spot-sandbox/internal/usecase/spots_profile"
)

// DbscanProfile is the resolver for the dbscanProfile field.
func (r *clusterElementResolver) DbscanProfile(ctx context.Context, obj *model.ClusterElement) (*model.DbscanProfile, error) {
	dpr := dbscan_profile_mysql.New(r.DB)
	dpf := dbscan_profile_finder_mysql.New(r.DB)
	dpuc := dbscan_profile.New(dpr, dpf)

	dp, err := dpuc.Get(obj.DbscanProfileID)
	if err != nil {
		return nil, err
	}
	return dbscan_profile_graph.Marshal(dp), nil
}

// SpotsProfile is the resolver for the spotsProfile field.
func (r *clusterElementResolver) SpotsProfile(ctx context.Context, obj *model.ClusterElement) (*model.SpotsProfile, error) {
	spr := spots_profile_mysql.New(r.DB)
	spf := spots_profile_finder_mysql.New(r.DB)
	spuc := spots_profile.New(spr, spf)

	sp, err := spuc.Get(obj.SpotsProfileID)
	if err != nil {
		return nil, err
	}
	return spots_profile_graph.Marshal(sp), nil
}

// Spot is the resolver for the spot field.
func (r *clusterElementResolver) Spot(ctx context.Context, obj *model.ClusterElement) (*model.Spot, error) {
	sr := spot_mysql.New(r.DB)
	sf := spot_finder_mysql.New(r.DB)
	suc := spot.New(sr, sf, r.GMC)

	s, err := suc.Get(obj.SpotID)
	if err != nil {
		return nil, err
	}
	return spot_graph.Marshal(s), nil
}

// CreateDbscanProfile is the resolver for the createDbscanProfile field.
func (r *mutationResolver) CreateDbscanProfile(ctx context.Context, input model.NewDbscanProfile) (*model.DbscanProfile, error) {
	dpr := dbscan_profile_mysql.New(r.DB)
	dpf := dbscan_profile_finder_mysql.New(r.DB)
	dpuc := dbscan_profile.New(dpr, dpf)

	i, err := dpr.NextIdentifier()
	if err != nil {
		return nil, err
	}
	p := dbscan_profile_graph.UnmarshalPreferences(input)
	if err := dpuc.Save(i, p); err != nil {
		return nil, err
	}
	dp, err := dpuc.Get(i)
	if err != nil {
		return nil, err
	}
	return dbscan_profile_graph.Marshal(dp), nil
}

// CreateSpotsProfile is the resolver for the createSpotsProfile field.
func (r *mutationResolver) CreateSpotsProfile(ctx context.Context, input model.NewSpotsProfile) (*model.SpotsProfile, error) {
	spr := spots_profile_mysql.New(r.DB)
	spf := spots_profile_finder_mysql.New(r.DB)
	spuc := spots_profile.New(spr, spf)

	i, err := spr.NextIdentifier()
	if err != nil {
		return nil, err
	}
	p := spots_profile_graph.UnmarshalPreferences(input)
	if err := spuc.Save(i, p); err != nil {
		return nil, err
	}
	sp, err := spuc.Get(i)
	if err != nil {
		return nil, err
	}
	return spots_profile_graph.Marshal(sp), nil
}

// CreateSpot is the resolver for the createSpot field.
func (r *mutationResolver) CreateSpot(ctx context.Context, input model.LatLng) (*model.Spot, error) {
	sr := spot_mysql.New(r.DB)
	sf := spot_finder_mysql.New(r.DB)
	suc := spot.New(sr, sf, r.GMC)

	i, err := sr.NextIdentifier()
	if err != nil {
		return nil, err
	}
	latlng := common.LatLng{Lat: input.Lat, Lng: input.Lng}
	if err := suc.Save(i, latlng); err != nil {
		return nil, err
	}
	s, err := suc.Get(i)
	if err != nil {
		return nil, err
	}
	return spot_graph.Marshal(s), nil
}

// Spots is the resolver for the spots field.
func (r *queryResolver) Spots(ctx context.Context) ([]*model.Spot, error) {
	sr := spot_mysql.New(r.DB)
	sf := spot_finder_mysql.New(r.DB)
	suc := spot.New(sr, sf, r.GMC)

	sis, err := suc.ListAllSpots(spot_finder.FilteringOptions{})
	if err != nil {
		return nil, err
	}
	sMap, err := suc.BulkGet(sis)
	if err != nil {
		return nil, err
	}
	ss := make([]*model.Spot, len(sis))
	for i, v := range sis {
		ss[i] = spot_graph.Marshal(sMap[v])
	}
	return ss, nil
}

// DbscanProfiles is the resolver for the dbscanProfiles field.
func (r *queryResolver) DbscanProfiles(ctx context.Context) ([]*model.DbscanProfile, error) {
	dpr := dbscan_profile_mysql.New(r.DB)
	dpf := dbscan_profile_finder_mysql.New(r.DB)
	dpuc := dbscan_profile.New(dpr, dpf)

	dpis, err := dpuc.ListAllDbscanProfiles()
	if err != nil {
		return nil, err
	}
	dpMap, err := dpr.BulkGet(dpis)
	if err != nil {
		return nil, err
	}
	dps := make([]*model.DbscanProfile, len(dpis))
	for i, v := range dpis {
		dps[i] = dbscan_profile_graph.Marshal(dpMap[v])
	}
	return dps, nil
}

// SpotsProfiles is the resolver for the spotsProfiles field.
func (r *queryResolver) SpotsProfiles(ctx context.Context) ([]*model.SpotsProfile, error) {
	spr := spots_profile_mysql.New(r.DB)
	spf := spots_profile_finder_mysql.New(r.DB)
	spuc := spots_profile.New(spr, spf)

	spis, err := spuc.ListAllSpotsProfiles()
	if err != nil {
		return nil, err
	}
	spMap, err := spr.BulkGet(spis)
	if err != nil {
		return nil, err
	}
	sps := make([]*model.SpotsProfile, len(spis))
	for i, v := range spis {
		sps[i] = spots_profile_graph.Marshal(spMap[v])
	}
	return sps, nil
}

// Spot is the resolver for the spot field.
func (r *queryResolver) Spot(ctx context.Context, key int) (*model.Spot, error) {
	sr := spot_mysql.New(r.DB)
	sf := spot_finder_mysql.New(r.DB)
	suc := spot.New(sr, sf, r.GMC)

	s, err := suc.Get(spot_graph.UnmarshalIdentifier(key))
	if err != nil {
		return nil, err
	}
	return spot_graph.Marshal(s), nil
}

// SpotsProfile is the resolver for the spotsProfile field.
func (r *queryResolver) SpotsProfile(ctx context.Context, key int) (*model.SpotsProfile, error) {
	spr := spots_profile_mysql.New(r.DB)
	spf := spots_profile_finder_mysql.New(r.DB)
	spuc := spots_profile.New(spr, spf)

	sp, err := spuc.Get(spots_profile_graph.UnmarshalIdentifier(key))
	if err != nil {
		return nil, err
	}
	return spots_profile_graph.Marshal(sp), nil
}

// DbscanProfile is the resolver for the dbscanProfile field.
func (r *queryResolver) DbscanProfile(ctx context.Context, key int) (*model.DbscanProfile, error) {
	dpr := dbscan_profile_mysql.New(r.DB)
	dpf := dbscan_profile_finder_mysql.New(r.DB)
	dpuc := dbscan_profile.New(dpr, dpf)

	dp, err := dpuc.Get(dbscan_profile_graph.UnmarshalIdentifier(key))
	if err != nil {
		return nil, err
	}
	return dbscan_profile_graph.Marshal(dp), nil
}

// Dbscan is the resolver for the dbscan field.
func (r *queryResolver) Dbscan(ctx context.Context, param model.DbscanParam) ([]*model.ClusterElement, error) {
	dpr := dbscan_profile_mysql.New(r.DB)
	spr := spots_profile_mysql.New(r.DB)
	sr := spot_mysql.New(r.DB)
	cs := domain_service.NewClusteringService(ctx, r.GMC, r.DiCC, r.DuCC)
	ceuc := cluster_element.New(sr, dpr, spr, cs)

	ces, err := ceuc.Calc(
		dbscan_profile_graph.UnmarshalIdentifier(param.DbscanProfileKey),
		spots_profile_graph.UnmarshalIdentifier(param.SpotsProfileKey),
	)
	if err != nil {
		return nil, err
	}
	return cluster_element_graph.BatchMarshal(ces), nil
}

// Spots is the resolver for the spots field.
func (r *spotsProfileResolver) Spots(ctx context.Context, obj *model.SpotsProfile) ([]*model.Spot, error) {
	sr := spot_mysql.New(r.DB)
	sf := spot_finder_mysql.New(r.DB)
	suc := spot.New(sr, sf, r.GMC)

	sMap, err := suc.BulkGet(obj.SpotKeys)
	if err != nil {
		return nil, err
	}
	result := make([]*model.Spot, len(obj.SpotKeys))
	for i, v := range obj.SpotKeys {
		result[i] = spot_graph.Marshal(sMap[v])
	}
	return result, nil
}

// ClusterElement returns ClusterElementResolver implementation.
func (r *Resolver) ClusterElement() ClusterElementResolver { return &clusterElementResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SpotsProfile returns SpotsProfileResolver implementation.
func (r *Resolver) SpotsProfile() SpotsProfileResolver { return &spotsProfileResolver{r} }

type clusterElementResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type spotsProfileResolver struct{ *Resolver }
