version: 3

tasks:
  redis:
    cmds:
      - cd tools/redis && docker-compose up -d
  mysql:
    cmds:
      - cd tools/mysql && docker-compose up -d
  docker:up:
    cmds:
      - task: redis
      - task: mysql
  docker:clean:
    cmds:
      - docker kill scapp_redis
      - docker kill scapp_mysql
      - docker system prune -f
  qlgen:
    cmds: 
      - go mod download all
      - go generate ./...