version: '3'
services:
  dev:
    image: node
    volumes:
      - ./:/my
    working_dir: /my/react-app
    command: sh -c "npm install && npm run build && npm run dev"
    ports:
      - "3000:3000"
#     tty: true